spring:
  application:
    name: EUREKA-SERVER
  profiles:
    active: prod
server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://13.127.125.180:8761/eureka
  server:
    waitTimeInMsWhenSyncEmpty: 0
    enableSelfPreservation: false
    maxThreadsForPeerReplication: 0


